---
version: '3.7'

services:

  db:
    image: mysql:latest #5.7.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbUserPassword
      MYSQL_DATABASE: db_work12
    ports:
      - 3306:3306
    volumes:
      - share:/root/share

  app:
    image: dtimerman/work12:latest
    restart: always
    ports:
      - 8080:8080