---
version: '2'

services:

  db:
    image: mysql:latest #5.7.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbUserPassword
      MYSQL_DATABASE: db_work12
    ports:
      - "3306:3306"

  app:
    image: dtimerman/work12:latest
    restart: always
    volumes:
      - ./share:/root/share

  prod:
    image: dtimerman/work12_prod:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./share:/root/share

