---
# tasks file for package_project_role
- name: Package project
  apt: name={{item}} state=present
  with_items:
    - default-jdk
    - git
    - maven

- name: Git project is cloned
  git:
    clone: yes
    repo: {project_git}
    dest: {project_folder}

- name: Ensure package project
  command: mvn -f {{project_folder}}/pom.xml package

- name: Store packaged file
  fetch:
    src: {project_folder} /target/ {package_file_name}
    dest: {shared_master_folder}
    flat: yes
