---
# tasks file for web_server_role
- name: Tomcat9 is present in prod
  apt:
    name: tomcat9
    state: present

- name: Copy file to tomcat9 webapps
  synchronize:
    src: "{ shared_master_folder }/hello-1.0.war"
    dest: /var/lib/tomcat9/webapps/
