---
- name: Install dev
  hosts: dev
  become: yes
  tasks:
  - name: Default-jdk is present in dev
    apt:
      name: default-jdk
      state: present
  - name: Maven is present in dev
    apt:
      name: maven
      state: present
  - name: Git is present in dev
    apt:
      name: git
      state: present
  - name: Git project is cloned
    git:
      clone: yes
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /root/work8/boxfuse-sample-java-war-hello/
  - name: Ensure package project
    command: mvn -f /root/work8/boxfuse-sample-java-war-hello/pom.xml package
  - name: Store file into /root/work8/boxfuse-sample-java-war-hello/target/hello-1.0.war
    fetch:
      src: /root/work8/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/
      flat: yes

- name: Install prod
  hosts: prod
  become: yes
  tasks:
  - name: Tomcat9 is present in prod
    apt:
      name: tomcat9
      state: present
  - name: Copy file to /var/lib/tomcat9/webapps/
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
      follow: yes
