---
- name: Install dev
  hosts: dev
  become: yes
  tasks:
  - name: default-jdk is present in dev
    apt:
      name: default-jdk
      state: present
  - name: tomcat9 is present in dev
    apt:
      name: tomcat9
      state: present
  - name: maven is present in dev
    apt:
      name: maven
      state: present
  - name: git is present in dev
    apt:
      name: git
      state: present
  - name: run a dev script
    script: work8-dev-script.sh
  - name: store file into /root/work8/boxfuse-sample-java-war-hello/target/hello-1.0.war
    fetch:
      src: /root/work8/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/

- name: Install prod
  hosts: prod
  become: yes
  tasks:
  - name: tomcat9 is present in prod
    apt:
      name: tomcat9
      state: present
  - name: copy file to /var/lib/tomcat9/webapps/
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
      follow: yes
