---
version: '3.7'
services:
  dev:
    build:
      context: dev/

  prod:
    build:
      context: prod/
    ports:
      - "80:8080"
    volumes:
      - /root/work7_shared_webapps:/opt/tomcat/webapps
