---
version: '3.7'
services:
  dev:
    build:
      context: dev/
    volumes:
      - work7_volume:/root/work7_shared_webapps_dev/

  prod:
    build:
      context: prod/
    ports:
      - "80:8080"
    volumes:
      - work7_volume:/opt/tomcat/webapps

volumes:
  work7_volume: