---
version: '3.7'
services:
  dev:
    build:
      context: dev/
    ports:
      - "8081:8080"

  prod:
    build:
      context: prod/
    volumes:
      - /root/work7_shared_webapps:/var/apache-tomcat-10.0.23/webapps
